- name: User Setup
  ansible.builtin.import_role:
    name: common
    tasks_from: user_setup

- name: Install Maven and Java
  ansible.builtin.import_role:
    name: common
    tasks_from: java

- name: Install MySQL client for shipping_version
  ansible.builtin.import_role:
    name: common
    tasks_from: mysql_setup

- name: Systemd service start
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd