- name: Install and Setup nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: Setup user
  ansible.builtin.import_role:
    name: common
    tasks_from: = user_setup

- name: Setup MongoDB
  ansible.builtin.import_role:
    name: common
    tasks_from: = mongodb_setup

- name: Systemd reset
  ansible.builtin.import_role:
    name: common
    tasks_from: = systemd