- name: Configure YUM Repos from the script provided by vendor
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: Configure YUM Repos for RabbitMQ
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: Install RabbitMQ.
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: present

- name: Start and enable RabbitMQ
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Add user and password
  ansible.builtin.command: "rabbitmqctl add_user roboshop {{rabbitmq_password}}"

- name: Set permissions
  ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"