- name: Disable the current MySQL version
  ansible.builtin.command: dnf module disable mysql

- name: Copy the mysql repo vars_files
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL
  ansible.builtin.package:
    name: mysql-community-server
    state: present

- name: Start and enable mysql
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Setup root password to MySQL
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1