- name: Install MySQL in shipping
  ansible.builtin.package:
    name: mysql
    state: present

- name: Get the schema data from MySQL
  ansible.builtin.shell: mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME='cities'"
  register: SCHEMA_NAME

- name: Check if data is loaded to mysql or not
  ansible.builtin.debug:
    msg: "Schema output: {{SCHEMA_NAME.stdout}}"

- name: Load data to mysql
  ansible.builtin.shell: "mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} < /app/schema/{{Module}}.sql"
  when: SCHEMA_NAME.stdout != "1"