- name: Disable current nodejs version
  ansible.builtin.command: dnf module disable nodejs -y

- name: Enable current nodejs version 18
  ansible.builtin.command: dnf module enable nodejs:18 -y

- name: Install nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: Install the application dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app