- name: Install python in payment
  ansible.builtin.package:
    name: {{item}}
    state: present
  loop:
  - python36
  - gcc
  - python3-devel

- name: Install dependencies
  ansible.builtin.command: pip3.6 install -r requirements.txt
  args:
    chdir: /app