- name: "Copy the {{Module}}.service file"
  ansible.builtin.template:
    src: "{{Module}}.service.j2"
    dest: /etc/systemd/system/catalogue.service

- name: System daemon-reload
  ansible.builtin.systemd_service:
    daemon-reload: true

- name: "Start and enable the {{Module}} service"
  ansible.builtin.service:
    name: "{{Module}}"
    state: restarted
    enabled: yes