- name: Add user roboshop
  ansible.builtin.user:
    name: roboshop

- name: Recursively remove the app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: "Download the {{Module}} application code"
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{Module}}.zip"
    dest: /tmp

- name: "Unzip the {{Module}} zip file"
  ansible.builtin.unarchive:
    src: "/tmp/{{Module}}.zip"
    dest: /app
    remote_src: yes