- name: Add user roboshop
  ansible.builtin.user:
    name: roboshop

- name: Recursively remove the app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: "Download the {{Module}} application code"
  ansible.builtin.get_url:
    src: https://roboshop-builds.s3.amazonaws.com/{{Module}}.zip
    dest: /tmp

- name: "Unzip the {{Module}} zip file"
  ansible.builtin.unarchive:
    path: "/tmp/{{Module}}.zip"
    dest: /app
    remote_src: yes

- name: Install the application dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app
